### ISSUE TITLE
"Bezpečnost"

### ISSUE THREAD

**Issue by MiloshCZ** [martinius96/RFID-otvaranie-dveri#1]
Jen by bylo dobré upozornit, že to čte jen UIN, který je možné duplikovat. Dále asi není vhodné v databázi ukládat přímo čísla karet (opět po úniku čísel z databáze je možné vytvářet duplikáty).

Jako ukázka toho, že to jde, to je dobré, ale na vstup do domu bych to nepoužil

**Comment by martinius96** [comment]
Je to jeden zo spôsobov ako je to možné urobiť. Platená verzia využíva už hash adries kariet, overuje aj user-agent hodnotu, i špeciálny string, ktorý sa musí zhodovať ako na NodeMCU tak i v PHP pri prijatí dát. Ak nie sú preukázané všetky parametre/sú chybné, nedôjde ani k overovaniu adresy podľa databázy.
